In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
#Define Vocabulary size
voc_size=10000

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9183, 6934, 7649, 1725],
 [9183, 6934, 7649, 7545],
 [9183, 2748, 7649, 2467],
 [7021, 8267, 3682, 9513, 6176],
 [7021, 8267, 3682, 9513, 8196],
 [8415, 9183, 2782, 7649, 5710],
 [1009, 5253, 8251, 9513]]

In [5]:
# # word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [9]:
## pre defines padding done at front post at last maxlen = max no. of words in input
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9183 6934 7649 1725]
 [   0    0    0    0 9183 6934 7649 7545]
 [   0    0    0    0 9183 2748 7649 2467]
 [   0    0    0 7021 8267 3682 9513 6176]
 [   0    0    0 7021 8267 3682 9513 8196]
 [   0    0    0 8415 9183 2782 7649 5710]
 [   0    0    0    0 1009 5253 8251 9513]]


In [10]:
## feature representation
dim=10

In [13]:
## Adding Embedding Layer
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')


In [14]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 567ms/step


array([[[-0.04428979, -0.03228656, -0.00116849,  0.04516577,
          0.02380568, -0.0144779 ,  0.04095181,  0.00395126,
          0.02790331,  0.03378734],
        [-0.04428979, -0.03228656, -0.00116849,  0.04516577,
          0.02380568, -0.0144779 ,  0.04095181,  0.00395126,
          0.02790331,  0.03378734],
        [-0.04428979, -0.03228656, -0.00116849,  0.04516577,
          0.02380568, -0.0144779 ,  0.04095181,  0.00395126,
          0.02790331,  0.03378734],
        [-0.04428979, -0.03228656, -0.00116849,  0.04516577,
          0.02380568, -0.0144779 ,  0.04095181,  0.00395126,
          0.02790331,  0.03378734],
        [ 0.04960718,  0.04386182, -0.0258824 ,  0.01066508,
          0.01235526, -0.00278071, -0.01883524,  0.00901039,
         -0.03089808, -0.0242082 ],
        [-0.04131757, -0.03647358,  0.04128131,  0.01821962,
          0.01137821,  0.03218604, -0.03825767,  0.02480442,
         -0.0096632 ,  0.01873827],
        [-0.02017554, -0.03359561, -0.04847852,  0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 9183, 6934, 7649, 1725], dtype=int32)

In [19]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step


array([[[-0.04428979, -0.03228656, -0.00116849,  0.04516577,
          0.02380568, -0.0144779 ,  0.04095181,  0.00395126,
          0.02790331,  0.03378734],
        [-0.04428979, -0.03228656, -0.00116849,  0.04516577,
          0.02380568, -0.0144779 ,  0.04095181,  0.00395126,
          0.02790331,  0.03378734],
        [-0.04428979, -0.03228656, -0.00116849,  0.04516577,
          0.02380568, -0.0144779 ,  0.04095181,  0.00395126,
          0.02790331,  0.03378734],
        [-0.04428979, -0.03228656, -0.00116849,  0.04516577,
          0.02380568, -0.0144779 ,  0.04095181,  0.00395126,
          0.02790331,  0.03378734],
        [ 0.04960718,  0.04386182, -0.0258824 ,  0.01066508,
          0.01235526, -0.00278071, -0.01883524,  0.00901039,
         -0.03089808, -0.0242082 ],
        [-0.04131757, -0.03647358,  0.04128131,  0.01821962,
          0.01137821,  0.03218604, -0.03825767,  0.02480442,
         -0.0096632 ,  0.01873827],
        [-0.02017554, -0.03359561, -0.04847852,  0.0